### ISSUE TITLE
Compability with the next ha version

### ISSUE THREAD

**Issue by RubenKelevra** [Limych/ha-apparent-temperature#74]
I tried the current beta for 2022.06 and there's an import error blocking this plugin:

```
2022-05-29 11:54:11 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config.py", line 877, in async_process_component_config
platform = p_integration.get_platform(domain)
File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/config/custom_components/temperature_feels_like/sensor.py", line 13, in <module>
from homeassistant.components.history import LazyState
ImportError: cannot import name 'LazyState' from 'homeassistant.components.history' (/usr/src/homeassistant/homeassistant/components/history/__init__.py)
```

**Comment by markmghali** [comment]
yes same issue here after upgrading to 2022.6


Configuration invalid!

Platform error sensor.temperature_feels_like - cannot import name 'LazyState' from 'homeassistant.components.history' (/usr/src/homeassistant/homeassistant/components/history/__init__.py)
Platform error sensor.temperature_feels_like - cannot import name 'LazyState' from 'homeassistant.components.history' (/usr/src/homeassistant/homeassistant/components/history/__init__.py)
Platform error sensor.temperature_feels_like - cannot import name 'LazyState' from 'homeassistant.components.history' (/usr/src/homeassistant/homeassistant/components/history/__init__.py)
Platform error sensor.temperature_feels_like - cannot import name 'LazyState' from 'homeassistant.components.history' (/usr/src/homeassistant/homeassistant/components/history/__init__.py)

**Comment by xabaras75** [comment]
Same for me after 2022.6 updating

**Comment by tamimology** [comment]
Same here. I had to disable it for now in order to successfully validate my configuration.yaml and restart HA

**Comment by ugenit** [comment]
Commenting off or removing line 13 in
config\custom_components\temperature_feels_like\sensor.py  

#from homeassistant.components.history import LazyState

Seems to have fixed the issue

**Comment by Zen3515** [comment]
You have to edit line 13 in
/config/custom_components/temperature_feels_like/sensor.py

from

```python
from homeassistant.components.history import LazyState
```

to

```python
from homeassistant.components.recorder.models import LazyState
```

**Comment by Patrick1610** [comment]
> You have to edit line 13 in /config/custom_components/temperature_feels_like/sensor.py
> 
> from
> 
> ```python
> from homeassistant.components.history import LazyState
> ```
> 
> to
> 
> ```python
> from homeassistant.components.recorder.models import LazyState
> ```

Awesome that you found this solution! 

@Limych will this fix be implemented shortly? In that case I won’t bother changing code myself but wait patiently 👌🏼
